### ISSUE TITLE
in win8.1x64 the client isn't closing properly. 

### ISSUE THREAD

**Issue by gendalv** [Noxwizard/dnscrypt-winclient#18]
i'm using win8.1x64 always in desktop mode.

after closing dnscrypt-winclient.exe - it always stays in the process list .
if i'll open&close another session of the client - it adds, so then it would be 2 processes of dnscrypt-winclient.exe, they never close, so i have to kill manually all of them each time in the task manager

**Comment by Noxwizard** [comment]
I am not able to replicate this. I have tested it on two different Windows 8.1 x64 systems.
