### ISSUE TITLE
WinClient always crash in Windows 10 build 1511

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [Noxwizard/dnscrypt-winclient#26]
After I upgrade to Windows 10 build 1511, WinClient always crash when I launch it, and I get following massage:
![dnscrypt winclient doesn t work](https://cloud.githubusercontent.com/assets/10364351/11502467/fdac74f0-9875-11e5-9318-73f159eab2d1.png)
>*“DNSCrypt Proxy Client is ceased to work”*
>*“Windows is collecting the detail information about this problem. This may need several minutes...”*

**Comment by Noxwizard** [comment]
Was it running fine under Windows 10 build 10240? That's what's running on mine and it works fine.

**Comment by KrasnayaPloshchad** [comment]
I tested again just now, it works for me without any connect, but when I connected to the Internet, the problem is still there.

**Comment by KrasnayaPloshchad** [comment]
Now the client works for me. but I don’t know why. Maybe I have just reinstalled a WLAN driver some days ago, which caused the problem.

**Comment by KrasnayaPloshchad** [comment]
Now the client works for me. but I don’t know why. Maybe I have just reinstalled a WLAN driver some days ago, which caused the problem.

**Comment by KrasnayaPloshchad** [comment]
Now the client works for me. but I don’t know why. Maybe I have just reinstalled a WLAN driver some days ago, which caused the problem after I upgraded to the build 10240.

**Comment by KrasnayaPloshchad** [comment]
Now the problem is appearing again, but I can’t found the reason anyway.

**Comment by Noxwizard** [comment]
I am still unable to reproduce this. It runs fine for me on Windows 10 1511 build 10586.104.

**Comment by KrasnayaPloshchad** [comment]
Oh, I remembered I’m using Windows 10 Home China Edition. I don’t know whether this got affect to me.

**Comment by KrasnayaPloshchad** [comment]
This client is still crash after I got KB3147458. Here is a report generated by system, found in Control Panel. I hope this would help.

源 (source)
DNSCrypt Proxy Client

摘要 (summary)
已停止工作 (Stopped working)

日期 (date)
‎2016.‎4.‎16 15:15

状态 (status0
已发送报告 (sent report)

描述 (description)
Stopped working

问题签名 (issue signature)
问题事件名称 (name of issue):	CLR20r3
问题签名 01:	dnscrypt-winclient.exe
问题签名 02:	1.1.0.0
问题签名 03:	5636c762
问题签名 04:	dnscrypt-winclient
问题签名 05:	1.1.0.0
问题签名 06:	5636c762
问题签名 07:	6
问题签名 08:	82
问题签名 09:	System.NullReferenceException
OS 版本 (OS version):	10.0.10586.2.0.0.768.99
区域设置 ID (locale ID):	2052

关于该问题的额外信息 (extra information about this problem)
存储段 ID (bucket ID):	aecca2cff127839b5430413cb90b7481 (128946353567)

**Comment by Noxwizard** [comment]
Yes, that helps. According to those WER entries (7 & 8), the error is in the PNPDeviceID check. It seems you have a network adapter that isn't actually Plug'n'Play compatible. I've added a check to handle that and have updated the binaries.

**Comment by KrasnayaPloshchad** [comment]
This app is still crashed after last commit.

Release build:
```
源
DNSCrypt Proxy Client

摘要
已停止工作

日期
‎2016.‎4.‎17 13:49

状态
已发送报告

描述
Stopped working

问题签名
问题事件名称:	CLR20r3
问题签名 01:	dnscrypt-winclient.exe
问题签名 02:	1.1.0.0
问题签名 03:	571272e4
问题签名 04:	dnscrypt-winclient
问题签名 05:	1.1.0.0
问题签名 06:	571272e4
问题签名 07:	6
问题签名 08:	52
问题签名 09:	System.NullReferenceException
OS 版本:	10.0.10586.2.0.0.768.99
区域设置 ID:	2052

关于该问题的额外信息
存储段 ID:	46924f5dab1c707ec8256c9203df15f0 (129074586646)
```
Debug build:
```源
DNSCrypt Proxy Client

摘要
已停止工作

日期
‎2016.‎4.‎17 13:52

状态
已发送报告

描述
Stopped working

问题签名
问题事件名称:	CLR20r3
问题签名 01:	dnscrypt-winclient.exe
问题签名 02:	1.1.0.0
问题签名 03:	571272db
问题签名 04:	dnscrypt-winclient
问题签名 05:	1.1.0.0
问题签名 06:	571272db
问题签名 07:	6
问题签名 08:	a7
问题签名 09:	System.NullReferenceException
OS 版本:	10.0.10586.2.0.0.768.99
区域设置 ID:	2052

关于该问题的额外信息
存储段 ID:	f70bfbb8ef58c584d0ac31bf3a4d379e (129074587873)
```

**Comment by Noxwizard** [comment]
Try the new build I just put out.

**Comment by KrasnayaPloshchad** [comment]
Still unhappy after 645dfca.

Release build:
```
源
DNSCrypt Proxy Client

摘要
已停止工作

日期
‎2016.‎4.‎18 5:10

状态
已发送报告

描述
Stopped working

问题签名
问题事件名称:	CLR20r3
问题签名 01:	dnscrypt-winclient.exe
问题签名 02:	1.1.0.0
问题签名 03:	5713d66f
问题签名 04:	System.Windows.Forms
问题签名 05:	2.0.0.0
问题签名 06:	56049533
问题签名 07:	2328
问题签名 08:	5d
问题签名 09:	System.ArgumentOutOfRange
OS 版本:	10.0.10586.2.0.0.768.99
区域设置 ID:	2052

关于该问题的额外信息
存储段 ID:	3469aa4a8dc65d7c38c4885323b8120d (129075053753)
```
Debug build:
```
源
DNSCrypt Proxy Client

摘要
已停止工作

日期
‎2016.‎4.‎18 5:14

状态
已发送报告

描述
Stopped working

问题签名
问题事件名称:	CLR20r3
问题签名 01:	dnscrypt-winclient.exe
问题签名 02:	1.1.0.0
问题签名 03:	5713d669
问题签名 04:	System.Windows.Forms
问题签名 05:	2.0.0.0
问题签名 06:	56049533
问题签名 07:	2328
问题签名 08:	5d
问题签名 09:	System.ArgumentOutOfRange
OS 版本:	10.0.10586.2.0.0.768.99
区域设置 ID:	2052

关于该问题的额外信息
存储段 ID:	e40f5834ce47c24f346802625f7b5393 (129075055703)
```

**Comment by Noxwizard** [comment]
According to that, there's an error to a call to set_selectedindex on one of the lists. Unfortunately, it doesn't provide any information about my application, just a global Windows Form exception. I've committed a new set of binaries with global exception handling which should include stack traces in the Event Log errors. You may see up to 3 entries in the Windows Event Log now when the application crashes. At least one of them should contain the stack trace that I need.

**Comment by KrasnayaPloshchad** [comment]
Release build:
```
源
DNSCrypt Proxy Client

摘要
已停止工作

日期
‎2016.‎4.‎18 13:54

状态
已发送报告

描述
Stopped working

问题签名
问题事件名称:	CLR20r3
问题签名 01:	dnscrypt-winclient.exe
问题签名 02:	1.1.0.0
问题签名 03:	57141d40
问题签名 04:	System.Windows.Forms
问题签名 05:	2.0.0.0
问题签名 06:	56049533
问题签名 07:	2328
问题签名 08:	5d
问题签名 09:	System.ArgumentOutOfRange
OS 版本:	10.0.10586.2.0.0.768.99
区域设置 ID:	2052

关于该问题的额外信息
存储段 ID:	8def5fba767fdcc8a0c50833898e96ed (129075307969)
```
Debug build:

On the first time, I got the following message:
![1](https://i.imgur.com/SJiXJX7.png)
_Translation: C:\Windows\System32\compobj.dll is not specified to run on Windows, or it including errors. Please try to reinstall the program with original installation medium, or contect your system administrator or software provider to get support. Error code: 0xc0000131_
Then the system let me install DirectPlay after I quit it. After installed DirectPlay, I opened the client again and got following messages:
![2](https://i.imgur.com/VTfDx3t.png)
![3](https://i.imgur.com/NDMpyny.png)
![4](https://i.imgur.com/SpjDCdX.png)
![5](https://i.imgur.com/89pOtUV.png)
![6](https://i.imgur.com/ZC0MLci.png)
![7](https://i.imgur.com/qBu3K5t.png)
![8](https://i.imgur.com/Kbwc4nZ.png)
All these builds were run as administrator via right click, after double click the debug build, it crash again.
```
问题签名
问题事件名称:	CLR20r3
问题签名 01:	dnscrypt-winclient.exe
问题签名 02:	1.1.0.0
问题签名 03:	57141d40
问题签名 04:	System.Windows.Forms
问题签名 05:	2.0.0.0
问题签名 06:	56049533
问题签名 07:	2328
问题签名 08:	5d
问题签名 09:	System.ArgumentOutOfRange
OS 版本:	10.0.10586.2.0.0.768.99
区域设置 ID:	2052

关于该问题的额外信息
存储段 ID:	8def5fba767fdcc8a0c50833898e96ed (129075307969)
```

**Comment by Noxwizard** [comment]
> Then the system let me install DirectPlay after I quit it. 

Why did you install DirectPlay? That is not required for this. I have no idea what those other DLLs are, .NET should not be loading them. It almost looks like something is attempting to inject into the process and failing. The only one of those messages that is related to this application is the last one saying that you don't have the resolver CSV file from the DNSCrypt website: https://download.dnscrypt.org/dnscrypt-proxy/dnscrypt-resolvers.csv

In your Windows Event Viewer, you should see several entries. Did you have those? They'll look like this:
![image](https://cloud.githubusercontent.com/assets/442353/14625311/8d95e814-05a7-11e6-9882-1e7546dc521f.png)

**Comment by KrasnayaPloshchad** [comment]
> The only one of those messages that is related to this application is the last one saying that you don't have the resolver CSV file from the DNSCrypt website: https://download.dnscrypt.org/dnscrypt-proxy/dnscrypt-resolvers.csv

The CSV file is already there, and I updated daily, but the client can’t load it when run as administrator.

>In your Windows Event Viewer, you should see several entries. Did you have those? They'll look like this:

Here is an event copied from Event Viewer:
Source: Windows Error Reporting  Record date: 2016.4.19 12:09:32
```
错误存储段 ，类型 0 (memory segment error, type 0)
事件名称: PCA2
响应: 不可用 (responce: unavailable)
Cab Id: 0

问题签名:
P1: dnscrypt-winservicemgr.exe
P2: 0.2.0.0
P3: dnscrypt-winservicemgr
P4: dnscrypt-winautoinstall
P5: 蒟Ʌ
P6: 100
P7: 0
P8: 
P9: 
P10: 
```
Source: dnscrypt-winclient  Record date: 2016.4.18 14:14:31
```
An application error occurred. Please contact the adminstrator with the following information:

InvalidArgument=“0”的值对于“SelectedIndex”无效。
参数名: SelectedIndex

Stack Trace:
   在 System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   在 dnscrypt_winclient.ApplicationForm.populate_Config_Form(Int32 index)
   在 dnscrypt_winclient.ApplicationForm.LoadConfig()
   在 dnscrypt_winclient.ApplicationForm..ctor()
   在 dnscrypt_winclient.Program.Main()
```

**Comment by Noxwizard** [comment]
Your CSV file is empty or otherwise corrupted. I've added checks to throw an error when it encounters that and to handle empty provider lists.

**Comment by KrasnayaPloshchad** [comment]
OK, after redownload the CSV, it works, but cannot install the service. See #27.
