### ISSUE TITLE
WinClient cannot install the service on Windows 10 build 10240

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [Noxwizard/dnscrypt-winclient#27]
When I open the client directly and click the Install button, I got the following massage:
![Error massage](https://i.imgur.com/52DXB5e.png)
_Translation: Accessing to “HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\dnscrypt-proxy\Parameters” is refused._
When I open the client via right ckick and choose “Run as administrator”, it massages some DLLs and CSV missing (as in #26).

**Comment by KrasnayaPloshchad** [comment]
This problem appeared to me for a long time before I updated to build 10240, and I have to run it as administrator. But after I updated to build 10240, it crashed mamy times even if run as administrator.

**Comment by Noxwizard** [comment]
The client must be run as an administrator on Windows 10 as Microsoft has increased the level of access required to make changes to the NIC settings and registry in Windows 10.

As for your other problems, I have finally been able to reproduce the. You seem to have placed the application in C:\Windows\System32\ or are using a shortcut with a "Start in" setting of C:\Windows\System32. Neither of those are supported by the .Net framework. You should be running the application from a normal location (Desktop, Program Files, etc...).

**Comment by KrasnayaPloshchad** [comment]
> You seem to have placed the application in C:\Windows\System32\ or are using a shortcut with a "Start in" setting of C:\Windows\System32.

No. I placed it in D:\ drive all the time.

**Comment by KrasnayaPloshchad** [comment]
OK, after 4376bd6, it works for me when I run as an administrator, but I think the Install button should be fully works with UAC before it can install or uninstall the service.

**Comment by KrasnayaPloshchad** [comment]
Is it possible to let the client require UAC when double click it?
