### ISSUE TITLE
Create 64bit builds

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [Noxwizard/dnscrypt-winclient#29]
Since [DNSCrypt 1.7.0](https://github.com/jedisct1/dnscrypt-proxy/releases/tag/1.7.0) released, this become necessary. The current 32bit build client seems work with 64bit build of dnscrypt-proxy, but plugin support absolutely ceased to work.

**Comment by Noxwizard** [comment]
There is no plugin support in this tool right now. All it does is show the descriptions, you can't change any settings related to them. The ability to see the plugin descriptions will probably go away in the future, making this moot.
