### ISSUE TITLE
Support dnscrypt-proxy v2

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [Noxwizard/dnscrypt-winclient#31]
Frank is developing dnscrypt-proxy 2.0.0, but your client doesn't support at all. Please add support for it.

**Comment by KrasnayaPloshchad** [comment]
See: https://github.com/jedisct1/dnscrypt-proxy/wiki

**Comment by zt3ph4n** [comment]
Are you going to update this project, or can you please refer another alternative for win?
Best regards, z

**Comment by Noxwizard** [comment]
You can find clients supporting v2 here: https://dnscrypt.info/implementations
